### ISSUE TITLE
Request to add "Time Does Tell: Self-Supervised Time-Tuning of Dense Image Representations"

### ISSUE THREAD

**Issue by SMSD75** [gaomingqi/Awesome-Video-Object-Segmentation#1]
Hi,

I would ask you to add this paper that has been accepted in ICCV23. Here is the link :

Paper : https://arxiv.org/abs/2308.11796
Repo : https://github.com/SMSD75/Timetuning

It is a self-supervised learning method for unsupervised video and image object segmentation.

**Comment by gaomingqi** [comment]
hello, thanks for your message and great work! Timetuning has been added to the ICCV 23 paper list! :smile:
