### ISSUE TITLE
Request to add papers

### ISSUE THREAD

**Issue by lxa9867** [gaomingqi/Awesome-Video-Object-Segmentation#2]
Hi,

Thanks for sharing this awesome project!

I would like to request to include the papers.

[cvpr 2024]
Towards Robust Audiovisual Segmentation in Complex Environments with Quantization-based Semantic Decomposition
arxiv: https://arxiv.org/abs/2310.00132
code: https://github.com/lxa9867/QSD

[emnlp 2023] 
Towards Noise-Tolerant Speech-Referring Video Object Segmentation: Bridging Speech and Text
arxiv: https://aclanthology.org/2023.emnlp-main.140.pdf

Thanks!!

**Comment by gaomingqi** [comment]
Hello,

Thanks for your message and great works, which have been added to the awesome list!!

Best

**Comment by lxa9867** [comment]
Hi, 

is it possible to incorporate "[R2-Bench: Benchmarking the Robustness of Referring Perception Models under Perturbations](https://arxiv.org/abs/2403.04924)" which is a benchmark for referring tasks, such as RVOS, RIS, AVOS. Thanks!

**Comment by gaomingqi** [comment]
Hello,

Sure, the benchmark has been added to the awesome list!!

Best

**Comment by lxa9867** [comment]
Thank you!!!
