### ISSUE TITLE
Why not Cuite?

### ISSUE THREAD

**Issue by HW140701** [gaomingqi/Awesome-Video-Object-Segmentation#7]
Putting the Object Back into Video Object Segmentation
https://arxiv.org/abs/2310.12982

**Comment by gaomingqi** [comment]
Thanks for your message. Cutie has been added (in Section: CVPR 2024) 

https://github.com/gaomingqi/Awesome-Video-Object-Segmentation/blob/f204b9e5b18d3d79d5794013c724086d735b1e57/README.md?plain=1#L202
